version: "2.3"

services:
  app:
    build: .
    image: quarkus/jharkendar
    mem_limit: 256m
    environment:
      - quarkus.datasource.username=root
      - quarkus.datasource.password=password
      - quarkus.datasource.jdbc.url=jdbc:mysql://database:3306/jharkendar
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - net
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=jharkendar
    networks:
      - net
    #    volumes:
    #      - $HOME/tmp/db/jharkendar.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
networks:
  net:
    driver: bridge